copy EventVB_I.dll %windir%\system32\
copy MSWINSCK.ocx %windir%\system32\
copy msdxm.ocx %windir%\system32\
copy winsock.dll %windir%\system32\
copy dx8vb.dll %windir%\system32\
copy dx7vb.dll %windir%\system32\
copy COMDLG32.OCX %windir%\system32\
copy COMCTL32.OCX %windir%\system32\
copy quartz.dll %windir%\system32\
copy stdole2.tlb %windir%\system32\
copy scrrun.dll %windir%\system32\ 
copy MSCOMCTL.OCX %windir%\system32\
copy MSADODC.OCX %windir%\system32\ 
copy odbccp32.dll %windir%\system32\
copy odbcbcp.dll %windir%\system32\
copy msjro.dll %windir%\system32\
copy SDXControl.ocx %windir%\system32\
copy wshom.ocx %windir%\system32\

regsvr32 /s wshom.ocx
regsvr32 /s SDXControl.ocx
regsvr32 /s msjro.dll
regsvr32 /s odbccp32.dll
regsvr32 /s odbcbcp.dll
regsvr32 /s MSADODC.OCX
regsvr32 /s MSCOMCTL.OCX
regsvr32 /s scrrun.dll
regsvr32 /s stdole2.tlb
regsvr32 /s quartz.dll
regsvr32 /s EventVB_I.dll
regsvr32 /s MSWINSCK.ocx
regsvr32 /s msdxm.ocx 
regsvr32 /s winsock.dll 
regsvr32 /s dx8vb.dll 
regsvr32 /s dx7vb.dll 
regsvr32 /s COMDLG32.OCX 
regsvr32 /s COMCTL32.OCX