-- Migration: fitur Mahjong -- kategori meja & transaksi bisa dibedakan billiard/mahjong,
-- harga mahjong pakai tabel sendiri (5 tier billiard sudah terpakai semua oleh kategori
-- billiard yang ada, jadi tidak bisa share ms_master_price).

ALTER TABLE `category_meja`
  ADD COLUMN `category_meja_type` ENUM('billiard','mahjong') NOT NULL DEFAULT 'billiard' AFTER `category_meja_name`;

ALTER TABLE `transaction`
  ADD COLUMN `transaction_category_type` ENUM('billiard','mahjong') NOT NULL DEFAULT 'billiard' AFTER `transaction_table`;

CREATE TABLE `ms_master_price_mahjong` (
  `master_price_id` INT(11) NOT NULL AUTO_INCREMENT,
  `master_price_days` ENUM('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday') NOT NULL,
  `master_price_time` INT(11) NOT NULL,
  `master_price_price` INT(11) NOT NULL DEFAULT 0,
  `master_price_price_2` INT(11) NOT NULL DEFAULT 0,
  `master_price_price_3` INT(11) NOT NULL DEFAULT 0,
  `master_price_price_4` INT(11) NOT NULL DEFAULT 0,
  `master_price_price_5` INT(11) NOT NULL DEFAULT 0,
  `ms_master_price_upload_status` ENUM('Y','N') NOT NULL DEFAULT 'N',
  PRIMARY KEY (`master_price_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- seed 7 hari x 24 jam = 168 baris, harga 0 (diisi lewat tab "Harga Mahjong" di app)
INSERT INTO `ms_master_price_mahjong` (`master_price_days`, `master_price_time`) VALUES
('Sunday',0),
('Sunday',1),
('Sunday',2),
('Sunday',3),
('Sunday',4),
('Sunday',5),
('Sunday',6),
('Sunday',7),
('Sunday',8),
('Sunday',9),
('Sunday',10),
('Sunday',11),
('Sunday',12),
('Sunday',13),
('Sunday',14),
('Sunday',15),
('Sunday',16),
('Sunday',17),
('Sunday',18),
('Sunday',19),
('Sunday',20),
('Sunday',21),
('Sunday',22),
('Sunday',23),
('Monday',0),
('Monday',1),
('Monday',2),
('Monday',3),
('Monday',4),
('Monday',5),
('Monday',6),
('Monday',7),
('Monday',8),
('Monday',9),
('Monday',10),
('Monday',11),
('Monday',12),
('Monday',13),
('Monday',14),
('Monday',15),
('Monday',16),
('Monday',17),
('Monday',18),
('Monday',19),
('Monday',20),
('Monday',21),
('Monday',22),
('Monday',23),
('Tuesday',0),
('Tuesday',1),
('Tuesday',2),
('Tuesday',3),
('Tuesday',4),
('Tuesday',5),
('Tuesday',6),
('Tuesday',7),
('Tuesday',8),
('Tuesday',9),
('Tuesday',10),
('Tuesday',11),
('Tuesday',12),
('Tuesday',13),
('Tuesday',14),
('Tuesday',15),
('Tuesday',16),
('Tuesday',17),
('Tuesday',18),
('Tuesday',19),
('Tuesday',20),
('Tuesday',21),
('Tuesday',22),
('Tuesday',23),
('Wednesday',0),
('Wednesday',1),
('Wednesday',2),
('Wednesday',3),
('Wednesday',4),
('Wednesday',5),
('Wednesday',6),
('Wednesday',7),
('Wednesday',8),
('Wednesday',9),
('Wednesday',10),
('Wednesday',11),
('Wednesday',12),
('Wednesday',13),
('Wednesday',14),
('Wednesday',15),
('Wednesday',16),
('Wednesday',17),
('Wednesday',18),
('Wednesday',19),
('Wednesday',20),
('Wednesday',21),
('Wednesday',22),
('Wednesday',23),
('Thursday',0),
('Thursday',1),
('Thursday',2),
('Thursday',3),
('Thursday',4),
('Thursday',5),
('Thursday',6),
('Thursday',7),
('Thursday',8),
('Thursday',9),
('Thursday',10),
('Thursday',11),
('Thursday',12),
('Thursday',13),
('Thursday',14),
('Thursday',15),
('Thursday',16),
('Thursday',17),
('Thursday',18),
('Thursday',19),
('Thursday',20),
('Thursday',21),
('Thursday',22),
('Thursday',23),
('Friday',0),
('Friday',1),
('Friday',2),
('Friday',3),
('Friday',4),
('Friday',5),
('Friday',6),
('Friday',7),
('Friday',8),
('Friday',9),
('Friday',10),
('Friday',11),
('Friday',12),
('Friday',13),
('Friday',14),
('Friday',15),
('Friday',16),
('Friday',17),
('Friday',18),
('Friday',19),
('Friday',20),
('Friday',21),
('Friday',22),
('Friday',23),
('Saturday',0),
('Saturday',1),
('Saturday',2),
('Saturday',3),
('Saturday',4),
('Saturday',5),
('Saturday',6),
('Saturday',7),
('Saturday',8),
('Saturday',9),
('Saturday',10),
('Saturday',11),
('Saturday',12),
('Saturday',13),
('Saturday',14),
('Saturday',15),
('Saturday',16),
('Saturday',17),
('Saturday',18),
('Saturday',19),
('Saturday',20),
('Saturday',21),
('Saturday',22),
('Saturday',23);

INSERT INTO `ms_menu` (`menu_code`, `menu_name`, `menu_active`) VALUES ('mahjong', 'Mahjong', 'Y');
